In [1]:
import numpy as np

# 행렬

## 행렬 연산 예시

## 내적과 element-wise 연산

내적(dot product)의 원소별(element-wise) 연산:
내적은 두 벡터의 각 원소의 곱을 모두 더해서 구함
element-wise 내적은 두 행렬 또는 벡터의 각 원소끼리 이루어짐

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)
elementwise_product = a * b

print("Vector a:", a)
print("\nVector b:", b)

print("\n", a[0]*b[0], "+", a[1]*b[1], "+", a[2]*b[2])
print("Dot product of a and b:", dot_product)

print("\nElement-wise product of a and b:", elementwise_product)


Vector a: [1 2 3]

Vector b: [4 5 6]

 4 + 10 + 18
Dot product of a and b: 32

Element-wise product of a and b: [ 4 10 18]


행렬 곱셈(matrix multiplication):
행렬 곱셈은 많은 추천 시스템 알고리즘에서 필수적인 연산임.
첫 번째 행렬의 행 원소에 두 번째 행렬의 열 원소를 곱하고 그 결과를 합산하는,
element-wise 내적의 반복임.

In [3]:
# Define two 2x2 matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Calculate the result matrix by matrix multiplication
C = np.matmul(A, B)

# Show the calculation of each element in the result matrix
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nC[0, 0] = A[0, 0] * B[0, 0] + A[0, 1] * B[1, 0] = (1 * 5) + (2 * 7) =", 1*5 + 2*7)
print("C[0, 1] = A[0, 0] * B[0, 1] + A[0, 1] * B[1, 1] = (1 * 6) + (2 * 8) =", 1*6 + 2*8)
print("C[1, 0] = A[1, 0] * B[0, 0] + A[1, 1] * B[1, 0] = (3 * 5) + (4 * 7) =", 3*5 + 4*7)
print("C[1, 1] = A[1, 0] * B[0, 1] + A[1, 1] * B[1, 1] = (3 * 6) + (4 * 8) =", 3*6 + 4*8)

print("\nResult Matrix C:")
print(C)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

C[0, 0] = A[0, 0] * B[0, 0] + A[0, 1] * B[1, 0] = (1 * 5) + (2 * 7) = 19
C[0, 1] = A[0, 0] * B[0, 1] + A[0, 1] * B[1, 1] = (1 * 6) + (2 * 8) = 22
C[1, 0] = A[1, 0] * B[0, 0] + A[1, 1] * B[1, 0] = (3 * 5) + (4 * 7) = 43
C[1, 1] = A[1, 0] * B[0, 1] + A[1, 1] * B[1, 1] = (3 * 6) + (4 * 8) = 50

Result Matrix C:
[[19 22]
 [43 50]]


## 전치 행렬

행렬의 전치:
행렬 전치는 단순히 행과 열을 바꾸어 주면 됨.
이 연산은 매우 단순하지만 자주 사용되는 작업으로,
추천 알고리즘에서는 대표적으로 MF, ALS 등에서 사용됨.

In [4]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

A_transpose = np.transpose(A)
print("Matrix A:\n", A)
print("\nTranspose of A:\n", A_transpose)


Matrix A:
 [[1 2]
 [3 4]
 [5 6]]

Transpose of A:
 [[1 3 5]
 [2 4 6]]


In [5]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

## 역행렬

행렬의 역행렬:
정사각형 행렬의 역행렬은 원 행렬에 곱하면 행렬의 단위 행렬이 나오는 행렬임.
선형 시스템(연립 방정식)의 해를 구하는 데 사용되거나,
추천에서는 SVD를 계산하는 데 사용됨

In [6]:
A = np.array([[1, 2],
              [3, 4]])

A_inverse = np.linalg.inv(A)
print("Matrix A:\n", A)
print("\nInverse of A:\n", A_inverse)
print("\nA * A_inverse (Identity matrix):\n", np.matmul(A, A_inverse))

Matrix A:
 [[1 2]
 [3 4]]

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

A * A_inverse (Identity matrix):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## 대각행렬

대각 행렬(diagonal matrix):
대각 행렬은 주 대각선 바깥의 모든 요소가 0인 정사각 행렬을 말함.
주 대각선은 행과 열 인덱스가 같은 원소로 구성됨.
대각선 행렬은 다양한 알고리즘에 사용되며 그 구조로 인해 계산을 단순화하는 데 사용됨.

In [7]:
import numpy as np

D = np.diag([1, 2, 3])
print("Diagonal matrix D:\n", D)


Diagonal matrix D:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


## 고유값과 고유 벡터

고유값과 고유 벡터:
정사각형 행렬 A의 고유 벡터는 0이 아닌 벡터로,
A를 곱하면 그 자체의 스칼라 배수가 되는 성질을 띰.
이 스칼라 배수 값을 고유값이라고 함.

In [8]:
A = np.array([[1, 2],
              [3, 4]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix A:\n", A)
print("\nEigenvalues of A:\n", eigenvalues)
print("\nEigenvectors of A:\n", eigenvectors)


Matrix A:
 [[1 2]
 [3 4]]

Eigenvalues of A:
 [-0.37228132  5.37228132]

Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## 랭크 (rank)

행렬 랭크:
행렬의 행렬계수는 행렬에서 선형적으로 독립적인 열 벡터(또는 행 벡터)의 최대 개수.
기하적으로는, 단위벡터에 한 선형변환이 가해졌을 때 도착하는 공간의 차원 수.

In [9]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

rank_A = np.linalg.matrix_rank(A)
print("Matrix A:\n", A)
print("\nRank of A:", rank_A)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank of A: 2


## SVD

특이값 분해(SVD):
SVD는 행렬을 U, Σ(시그마), V^T(V의 전치)의 세 행렬로 분해하는 데 사용되는 기법으로,
여기서 U와 V는 직교 행렬이고 Σ는 특이값이 포함된 대각선 행렬임.
SVD는 데이터의 차원을 줄이고, 노이즈를 제거하는 데도 사용되며,
추천 시스템의 맥락에서는 Latent Factor를 발견하는 데 사용할 수 있음

In [10]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

U, sigma, Vt = np.linalg.svd(A)

print("Matrix A:\n", A)
print("\nU:\n", U)
print("\nSingular values (Sigma):\n", sigma)
print("\nV transpose (Vt):\n", Vt)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

U:
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]

Singular values (Sigma):
 [1.68481034e+01 1.06836951e+00 3.33475287e-16]

V transpose (Vt):
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [11]:
Sigma = np.diag(sigma)
print("Diagonal matrix (Sigma):\n", Sigma)

Diagonal matrix (Sigma):
 [[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.33475287e-16]]


SVD 구성 요소(U, Σ, V^T)를 각각 곱하면, 원래 행렬 A를 재구성할 수 있음.

In [12]:
reconstructed_A = np.matmul(np.matmul(U, Sigma), Vt)
print("Reconstructed Matrix A from SVD components:\n", reconstructed_A)


Reconstructed Matrix A from SVD components:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# 유사도 메트릭

## 코사인 유사도와 유클리드 거리의 비교

In [13]:
# Compute Euclidean distance
def euclidean_distance(vec1, vec2):
    return np.sqrt(np.sum((vec1 - vec2) ** 2))

# Compute Cosine distance
def cosine_distance(vec1, vec2):
    dot_product = np.dot(vec1, vec2)
    norm_a = np.linalg.norm(vec1)
    norm_b = np.linalg.norm(vec2)
    return 1 - (dot_product / (norm_a * norm_b))

<img src='https://drive.google.com/uc?id=1uqdH-zznfHpf5Ae6hfNQwfkhmFV_lR-D' width="700" height ="200" /><br>

<img src='https://drive.google.com/uc?id=1PxgGhOp92df48brwEOsLSeQCigFjf4l9' width="700" height ="200" /><br>



아래 데이터프레임은 아래 3개의 문장을 단어별로 카운트해서 벡터로 만든 결과임.

"I like apples."
"I like oranges."
"I like apples. I really like apples."

In [14]:
import pandas as pd
import numpy as np

# Create a pandas DataFrame with the word vectors
data = {'I': [1, 1, 2], 'like': [1, 1, 2], 'apples': [1, 0, 2], 'oranges': [0, 1, 0], 'really': [0, 0, 1]}
df = pd.DataFrame(data)
df.index = [1,2,3]

display(df)

I  like  apples  oranges  really
1  1     1       1        0       0
2  1     1       0        1       0
3  2     2       2        0       1

문장 1과 문장 2는 동일한 구성을 갖는 대신 단어가 한 개 다름 (apples -> oranges).

문장 1과 문장 2 사이의 코사인 거리는 0.33으로, 벡터 방향에 약간의 차이가 있음을 시사함.
문장 1과 문장 2 사이의 유클리드 거리는 1.414로 단어 한 개가 다른 영향을 보여줌.


한편, 이 예시에서 문장 1과 문장 3은 동일한 단어를 공유하지만 반복으로 인해 벡터의 크기가 다름

문장 1과 문장 3 사이의 코사인 거리는 거의 0으로, 문장 3의 크기가 더 크지만 단어 분포 측면에서 유사하다는 것을 나타냄.
이는 코사인 유사성이 벡터의 크기에 민감하지 않다는 것을 보여줌

반면에 문장 1과 문장 3 사이의 유클리드 거리는 0보다 크며, 이는 두 문장 간의 크기 차이가 있음을 나타냄.
이는 유클리드 거리는 방향 뿐만 아니라 벡터의 크기에도 영향을 받음을 보여 줌.

In [15]:
# Compute Euclidean distance
def euclidean_distance(vec1, vec2):
    return np.sqrt(np.sum((vec1 - vec2) ** 2))

# Compute Cosine distance
def cosine_distance(vec1, vec2):
    dot_product = np.dot(vec1, vec2)
    norm_a = np.linalg.norm(vec1)
    norm_b = np.linalg.norm(vec2)
    return 1 - (dot_product / (norm_a * norm_b))

In [16]:
sentence1_vector = df.iloc[0].values
sentence2_vector = df.iloc[1].values
sentence3_vector = df.iloc[2].values

euclidean_dist_12 = euclidean_distance(sentence1_vector, sentence2_vector)
cosine_dist_12 = cosine_distance(sentence1_vector, sentence2_vector)

euclidean_dist_13 = euclidean_distance(sentence1_vector, sentence3_vector)
cosine_dist_13 = cosine_distance(sentence1_vector, sentence3_vector)

print(f"Euclidean distance between Sentence 1 and Sentence 2: {euclidean_dist_12}")
print(f"Cosine distance between Sentence 1 and Sentence 2: {cosine_dist_12}")

print(f"Euclidean distance between Sentence 1 and Sentence 3: {euclidean_dist_13}")
print(f"Cosine distance between Sentence 1 and Sentence 3: {cosine_dist_13}")

Euclidean distance between Sentence 1 and Sentence 2: 1.4142135623730951
Cosine distance between Sentence 1 and Sentence 2: 0.33333333333333326
Euclidean distance between Sentence 1 and Sentence 3: 2.0
Cosine distance between Sentence 1 and Sentence 3: 0.03923107716947705
